### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by Shailuc** [sreejithpillai/ExcelRecordReaderMapReduce#1]
Hi,

  I am working on the similar application which parses the input excel column wise and write the output to HDFS file ssytem, I downloaded the code base since it is Maven project I built it using maven and I can see two jars , ig I go to target and run hadoop jar  /target/ExcelRecordReaderMapReduce-0.0.1-SNAPSHOT-jar-with-dependencies.jar in out  . I get a error Exception in thread "main" java.lang.ClassNotFoundException: in
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:153)
could you please help me with this.

**Comment by Shailuc** [comment]
Hi,  
               Thanks for the inputs it was really helpfull, I had to pass the driver class name along with jar file  i.e hadoop jar /ExcelRecordReaderMapReduce-master/target/ExcelRecordReaderMapReduce-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.sreejithpillai.excel.mapreduce.ExcelDriver in out  .

my next is to  work on reading two different csv files related by a common  column name, I dont think I can do it in sigle mapper (passing splits for two different files in single mapper). Please provide some inputs.
