### ISSUE TITLE
Showing Error: java.lang.ClassNotFoundException: org.apache.poi.xssf.usermodel.XSSFWorkbook 

### ISSUE THREAD

**Issue by studhadoop** [sreejithpillai/ExcelRecordReaderMapReduce#2]
Once i gave Sample.xlsx this file as input it throen an error to use XSSFWorkbook instead of HSSFWorkbook. I changed the same and once I ran t it is showing 

Error: java.lang.ClassNotFoundException: org.apache.poi.xssf.usermodel.XSSFWorkbook
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at edu.am.bigdata.CustomInputFormat.Excel.ExcelParser.parseExcelData(ExcelParser.java:22)
    at edu.am.bigdata.CustomInputFormat.Excel.ExcelRecordReader.initialize(ExcelRecordReader.java:38)
    at org.apache.hadoop.mapreduce.lib.input.DelegatingRecordReader.initialize(DelegatingRecordReader.java:84)
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:548)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:786)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)

My maven contains

<dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi</artifactId>
        <version>3.7</version>
    </dependency>
    <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi-scratchpad</artifactId>
        <version>3.7</version>
    </dependency>
    <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi-ooxml</artifactId>
        <version>3.7</version>
    </dependency>
    <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi-ooxml-schemas</artifactId>
        <version>3.7</version>
    </dependency>

Can u please let me know what is the issue?

**Comment by IgnasJonuska** [comment]
Have you find out what was wrong?
